name: Build Engine
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            targetos: linux
            targetarch: amd64
          - os: ubuntu-22.04
            targetos: linux
            targetarch: i386
          - os: ubuntu-latest
            targetos: android
            targetarch: multiarch
          - os: ubuntu-latest
            targetos: nswitch
            targetarch: arm64
          - os: windows-latest
            targetos: win32
            targetarch: amd64
          - os: windows-2022
            targetos: win32
            targetarch: i386

    env:
      SDL_VERSION: 2.32.8
      FFMPEG_VERSION: 7.1
      GH_CPU_ARCH: ${{ matrix.targetarch }}
      GH_CPU_OS: ${{ matrix.targetos }}
      GH_CROSSCOMPILING: ${{ matrix.cross || false }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Make scripts executable
        run: chmod -R +x ./
        shell: bash

      - name: Install dependencies
        run: bash scripts/gha/deps_${{ matrix.targetos }}.sh

      - name: Build engine
        run: |
             export ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME
             bash scripts/gha/build_${{ matrix.targetos }}.sh

      - name: Upload engine (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.targetos  }}-${{ matrix.targetarch }}
          path: artifacts/*
